org.gradle.jvmargs=-Xmx3G
mod_id=tlmvision
mod_name=Touhou Little Maid: Vision
mod_version=0.1.0
mod_group_id=com.coolpick
mod_authors=Coolpick
mod_license=MIT
mod_description=Borrow maid sight and share views through the Third Eye bauble.
neo_version=21.1.217
parchment_mappings_version=2024.11.17
parchment_minecraft_version=1.21.1
